export const CASE_PERSON_WITH_DOSSIER_SELECT = `
  p.id,
  p.case_id,
  p.full_name,
  p.apparent_role,
  p.biography,
  p.created_at,
  p.updated_at,
  d.id AS dossier_id,
  d.phone_number AS dossier_phone_number,
  d.address AS dossier_address,
  d.height_cm AS dossier_height_cm,
  d.is_alive AS dossier_is_alive,
  d.prior_offenses AS dossier_prior_offenses,
  d.created_at AS dossier_created_at,
  d.updated_at AS dossier_updated_at,
  dp.dossier_number AS profile_dossier_number,
  dp.dossier_status AS profile_dossier_status,
  dp.classification_level AS profile_classification_level,
  dp.revision_number AS profile_revision_number,
  dp.generated_by_user_id AS profile_generated_by_user_id,
  dp.generated_at AS profile_generated_at,
  dp.last_reviewed_at AS profile_last_reviewed_at,
  dp.birth_date AS profile_birth_date,
  dp.birth_place AS profile_birth_place,
  dp.nationality AS profile_nationality,
  dp.gender AS profile_gender,
  dp.marital_status AS profile_marital_status,
  dp.occupation AS profile_occupation,
  dp.employer AS profile_employer,
  dp.education_level AS profile_education_level,
  dp.eye_color AS profile_eye_color,
  dp.hair_color AS profile_hair_color,
  dp.weight_kg AS profile_weight_kg,
  dp.identifying_marks AS profile_identifying_marks,
  dp.known_associates AS profile_known_associates,
  dp.risk_level AS profile_risk_level,
  dp.last_known_location AS profile_last_known_location,
  dp.photo_data_url AS profile_photo_data_url,
  dp.notes AS profile_notes
`;

function buildFallbackDossierNumber(row) {
  const caseCode = String(row.case_id || 0).padStart(4, "0");
  const personCode = String(row.id || 0).padStart(5, "0");
  return `DOS-${caseCode}-${personCode}`;
}

export function mapCasePersonWithDossier(row) {
  const fallbackDossierNumber = buildFallbackDossierNumber(row);

  return {
    id: row.id,
    caseId: row.case_id,
    fullName: row.full_name,
    apparentRole: row.apparent_role,
    biography: row.biography,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    dossier: {
      id: row.dossier_id || null,
      dossierNumber: row.profile_dossier_number || fallbackDossierNumber,
      dossierStatus: row.profile_dossier_status || "active",
      classificationLevel: row.profile_classification_level || "interno",
      revisionNumber: row.profile_revision_number || 1,
      generatedByUserId: row.profile_generated_by_user_id || null,
      generatedAt: row.profile_generated_at || row.dossier_created_at || null,
      lastReviewedAt: row.profile_last_reviewed_at || null,
      phoneNumber: row.dossier_phone_number || "",
      address: row.dossier_address || "",
      birthDate: row.profile_birth_date || "",
      birthPlace: row.profile_birth_place || "",
      nationality: row.profile_nationality || "",
      gender: row.profile_gender || "",
      maritalStatus: row.profile_marital_status || "",
      occupation: row.profile_occupation || "",
      employer: row.profile_employer || "",
      educationLevel: row.profile_education_level || "",
      eyeColor: row.profile_eye_color || "",
      hairColor: row.profile_hair_color || "",
      heightCm: row.dossier_height_cm,
      weightKg: row.profile_weight_kg,
      isAlive: row.dossier_is_alive === 0 ? false : true,
      identifyingMarks: row.profile_identifying_marks || "",
      knownAssociates: row.profile_known_associates || "",
      riskLevel: row.profile_risk_level || "unknown",
      lastKnownLocation: row.profile_last_known_location || "",
      photoDataUrl: row.profile_photo_data_url || "",
      priorOffenses: row.dossier_prior_offenses || "",
      notes: row.profile_notes || "",
      createdAt: row.dossier_created_at || null,
      updatedAt: row.dossier_updated_at || null,
    },
  };
}
